name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker-compose -f ./compose.yaml build
        images=("projekt-win-backend" "nginx" "mongo" "mongo-express")
        for image in "${images[@]}"; do
          docker tag ${image}:latest ${{ secrets.DOCKER_USERNAME }}/${image}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${image}:latest
        done
