name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker images
      run: docker-compose -f ./compose.yaml build
    - name: Tag and Push projekt-win-backend
      run: |
        docker tag projekt-win-backend:latest knusperking/projekt-win-backend:latest
        docker push knusperking/projekt-win-backend:latest
    - name: Tag and Push nginx
      run: |
        docker tag nginx:latest knusperking/nginx:latest
        docker push knusperking/nginx:latest
    - name: Tag and Push mongo
      run: |
        docker tag mongo:latest knusperking/mongo:latest
        docker push knusperking/mongo:latest
    - name: Tag and Push mongo-express
      run: |
        docker tag mongo-express:latest knusperking/mongo-express:latest
        docker push knusperking/mongo-express:latest
