name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build backend service
      run: docker-compose -f ./compose.yaml build backend
    - name: Tag and push Docker images
      run: |
        # Tag and push backend service
        docker tag flask_backend:builder ${{ secrets.DOCKER_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

        # Tag and push other services
        docker pull nginx:latest
        docker tag nginx:latest ${{ secrets.DOCKER_USERNAME }}/nginx:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

        docker pull mongo:latest
        docker tag mongo:latest ${{ secrets.DOCKER_USERNAME }}/mongo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mongo:latest

        docker pull mongo-express:latest
        docker tag mongo-express:latest ${{ secrets.DOCKER_USERNAME }}/mongo-express:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mongo-express:latest
