name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker images
      run: docker-compose -f ./compose.yaml build

    - name: List Docker images
      run: docker images

    - name: Tag and Push projekt-win-backend
      run: |
        IMAGE_NAME="knusperking/projekt-win_backend"
        IMAGE_TAG="latest"
        docker tag projekt-win_backend:latest $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1

    - name: Pull and Tag nginx
      run: |
        IMAGE_NAME="knusperking/nginx"
        IMAGE_TAG="latest"
        docker pull nginx:$IMAGE_TAG || true
        docker tag nginx:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Pull and Tag mongo
      run: |
        IMAGE_NAME="knusperking/mongo"
        IMAGE_TAG="latest"
        docker pull mongo:$IMAGE_TAG || true
        docker tag mongo:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Pull and Tag mongo-express
      run: |
        IMAGE_NAME="knusperking/mongo-express"
        IMAGE_TAG="latest"
        docker pull mongo-express:$IMAGE_TAG || true
        docker tag mongo-express:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: List Docker images after push
      run: docker images

    - name: Docker Hub Image Check
      run: |
        echo "Checking Docker Hub for images..."
        docker pull knusperking/projekt-win_backend:latest || echo "Failed to pull projekt-win_backend"
        docker pull knusperking/nginx:latest || echo "Failed to pull nginx"
        docker pull knusperking/mongo:latest || echo "Failed to pull mongo"
        docker pull knusperking/mongo-express:latest || echo "Failed to pull mongo-express"
